openapi: 3.0.0
info:
  title: watch
  version: '1.0'
servers:
  - url: 'http://localhost:8097'
    description: longwatch
paths:
  /admin/user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                fullname:
                  type: string
                  format: email
                  example: abc@gmail.com
                phone:
                  type: string
                  format: date
                  description: ngày sinh
                address:
                  type: string
                joninedat:
                  type: string
                status:
                  type: integer
                role:
                  type: string
                email:
                  type: string
                forgetcodedate:
                  type: string
                  format: date
                sex:
                  type: string
              required:
                - username
                - password
                - fullname
                - phone
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
  user/login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: login sucess!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  msg:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
              examples:
                sucess:
                  value:
                    status: 1
                    msg: tạo tài khoản thành công
                    data: {}
      description: user/admin login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: tên đăng nhập
                password:
                  type: string
              required:
                - username
                - password
        description: ''
    parameters: []
components:
  schemas:
    User:
      title: User Output
      type: object
      description: output api login
      x-examples:
        output Api:
          id: 1
          email: longtranvan15091999@gmail.com
          fullname: Tran Van Long
          phone: '0358172099'
          Sex: 1
          Address: Ha Noi
        example-2:
          username: Luong@gmail.com
          password: '122'
          fullname: Ninh van Luong
          phone: '0358172099'
          address: Hai Duong
          status: 1
          role: 1
          email: Luong@gmail.com
          sex: 1
          joinedat: '2021-02-01'
          createdby: Tran van Long
      properties:
        id:
          description: Unique identifier for the given user.
          type: integer
        username:
          type: string
        fullname:
          type: string
          format: email
        phone:
          format: date
          example: '1997-10-31'
          type: string
        Sex:
          type: integer
          description: Set to true if the user's email has been verified.
        Address:
          type: string
          format: date
          description: The date that the user was created.
        role:
          type: integer
          description: '1 la admin, 2 la khach hang'
        status:
          type: integer
      required:
        - id
        - username
        - fullname
        - phone
        - Sex
        - Address
